### ISSUE TITLE
Debug is enabled by default

### ISSUE THREAD

**Issue by robison** [rfarley3/Kibana#6]
Any thoughts about setting the output message level from the CLI? I can put together a quick PR if that helps.

**Comment by rfarley3** [comment]
I currently don't have a need for it, so it may be a while before I could get to it. I'd like to believe I'm easy going for accepting PRs, so feel free if you'd like to tackle it. Are you thinking about a `-v|--verbose` flag to enable debug output, but otherwise default to debug output as off?
